//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRANS_TBL
    {
        public int BRANSID { get; set; }
        public string BRANSAD { get; set; }
    }
}
