//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OkulOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dba_OkulOtomasyonuEntities : DbContext
    {
        public dba_OkulOtomasyonuEntities()
            : base("name=dba_OkulOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BRANS_TBL> BRANS_TBL { get; set; }
        public virtual DbSet<IL_TBL> IL_TBL { get; set; }
        public virtual DbSet<ILCE_TBL> ILCE_TBL { get; set; }
        public virtual DbSet<OGR_TBL> OGR_TBL { get; set; }
        public virtual DbSet<OGRT_TBL> OGRT_TBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VELI_TBL> VELI_TBL { get; set; }
        public virtual DbSet<AYAR_TBL> AYAR_TBL { get; set; }
        public virtual DbSet<OGRAYAR_TBL> OGRAYAR_TBL { get; set; }
    
        public virtual ObjectResult<AyarlarOgrenciler_Result> AyarlarOgrenciler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AyarlarOgrenciler_Result>("AyarlarOgrenciler");
        }
    
        public virtual ObjectResult<AyarlarOgretmenler_Result> AyarlarOgretmenler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AyarlarOgretmenler_Result>("AyarlarOgretmenler");
        }
    }
}
